### ISSUE TITLE
When particles are emitted, modifiers may not be initially applied

### ISSUE THREAD

**Issue by dancrevier** [jasonmitchell/supernova#2]
I've got a case where I've got a modifier that scales particles from .1 to .05. I've found that when I emit them, there's a frame where they flash large. I think this is because there isn't an update round between when I emit them and when they are drawn.

I've fixed it in my local repository by adding the following in ParticleEffect2D.Emit after initializing the particle:

```
                foreach (IModifier modifier in modifiers)
                    modifier.Update(0f, totalMilliseconds, 0, newParticle);
```

**Comment by jasonmitchell** [comment]
Well spotted.  Perhaps you could submit a pull request with the fix and I will merge it in?

**Comment by dancrevier** [comment]
Just submitted one. I'm a bit of a git noob, so hopefully I got it right.

**Comment by jasonmitchell** [comment]
Same here, looks good though.  I've merged it in and just need to update the NuGet package

**Comment by jasonmitchell** [comment]
I've updated the NuGet package to include your fix.  If you are using NuGet then you should be able to update that way.
